(() => {
  'use strict';

  const SOURCES = [
    { org: 'OHCHR', title: 'Fact-Finding Report: Human Rights Violations and Abuses, July–August 2024', meta: 'United Nations Human Rights Office · 12 Feb 2025', url: 'https://www.ohchr.org/sites/default/files/documents/countries/bangladesh/ohchr-fftb-hr-violations-bd.pdf' },
    { org: 'OHCHR', title: 'Preliminary Analysis of Recent Protests and Unrest in Bangladesh', meta: 'United Nations Human Rights Office · 16 Aug 2024', url: 'https://www.ohchr.org/sites/default/files/2024-08/OHCHR-Preliminary-Analysis-of-Recent-Protests-and-Unrest-in-Bangladesh-16082024_2.pdf' },
    { org: 'UNICEF', title: 'At least 32 children killed in Bangladesh violence', meta: 'UNICEF South Asia · 2 Aug 2024', url: 'https://www.unicef.org/press-releases/least-32-children-killed-bangladesh-violence' },
    { org: 'Amnesty', title: 'What happened at the quota-reform protests in Bangladesh?', meta: 'Amnesty International · July 2024', url: 'https://www.amnesty.org/en/latest/news/2024/07/what-is-happening-at-the-quota-reform-protests-in-bangladesh/' },
    { org: 'Amnesty', title: 'Thousands of protesters arrested arbitrarily', meta: 'Amnesty International · 2 Aug 2024', url: 'https://www.amnesty.org/en/documents/asa13/8388/2024/en/' },
    { org: 'The Daily Star', title: 'From quota to state reform — July Uprising timeline', meta: 'Chronology with linked reporting · 2018–5 Aug 2024', url: 'https://www.thedailystar.net/july-uprising/index.html' },
    { org: 'The Daily Star', title: '36 Days of July — reporting, testimony and investigations', meta: 'Multimedia archive · 2026', url: 'https://july36.thedailystar.net/' },
    { org: 'July Memorial Museum', title: 'July Mass Uprising photo and document archive', meta: 'Government of Bangladesh public archive', url: 'https://july36.gov.bd/archives/photo' },
    { org: 'The Business Standard', title: 'How the Bangladeshi diaspora supported the July movement from abroad', meta: 'Diaspora reporting, including Germany · 5 Sep 2024', url: 'https://www.tbsnews.net/features/panorama/how-bangladeshi-diaspora-supported-july-movement-abroad-935821' },
    { org: 'AP', title: 'Student leaders who led the uprising form the National Citizen Party', meta: 'Associated Press · 28 Feb 2025', url: 'https://apnews.com/article/7565d2860be1ed4c03bfd9a5beb4f539' },
    { org: 'BSS', title: 'National Citizen Party officially launched', meta: 'Bangladesh Sangbad Sangstha · 28 Feb 2025', url: 'https://www.bssnews.net/news-flash/250632' },
    { org: 'UN', title: 'Call for justice and protection after the transition', meta: 'United Nations Secretary-General · 5 Aug 2024', url: 'https://www.un.org/sg/en/content/sg/statements/2024-08-05/statement-attributable-the-spokesperson-for-the-secretary-general-bangladesh' }
  ];

  const bn = {
    archiveLabel:'জুলাই জ্ঞানভান্ডার', share:'শেয়ার', heroKicker:'বাংলাদেশ · ৫ জুন—৫ আগস্ট ২০২৪', heroTitle:'নীরবতার বিরুদ্ধে<br>জনতার অভ্যুত্থান', heroLead:'কোটা সংস্কারের ন্যায্য দাবি থেকে রাষ্ট্র সংস্কারের গণদাবি—তরুণদের সাহস, মানুষের সংহতি এবং ভয়াবহ দমন-পীড়নের মধ্য দিয়ে বদলে যাওয়া বাংলাদেশের ৩৬ দিনের দলিল।', explore:'টাইমলাইন দেখুন', readEvidence:'জাতিসংঘের তথ্য পড়ুন', scroll:'ইতিহাসের ভেতরে প্রবেশ করুন',
    methodKicker:'সম্পাদনা নীতি', methodTitle:'স্মৃতি, কিন্তু প্রমাণের ভিত্তিতে', methodText:'এই আর্কাইভ জাতিসংঘের মানবাধিকার দপ্তর, UNICEF, Amnesty International, সংবাদমাধ্যম ও উন্মুক্ত সরকারি আর্কাইভের তথ্য সমন্বয় করে তৈরি। নিহত ও আহতের সংখ্যা উৎস ও সময়ভেদে আলাদা; তাই প্রতিটি পরিসংখ্যান তার উৎস ও সময়সীমাসহ উপস্থাপন করা হয়েছে।', balanceText:'রাষ্ট্রীয় দমন-পীড়নের পাশাপাশি আন্দোলনের সময় ও ৫ আগস্টের পর সংঘটিত প্রতিশোধমূলক সহিংসতা, পুলিশ–আওয়ামী লীগ সদস্য এবং ধর্মীয় ও জাতিগত সংখ্যালঘুদের ওপর হামলাও ন্যায়বিচারের আওতায় আসতে হবে।',
    factsKicker:'প্রমাণিত মাত্রা', factsTitle:'সংখ্যার পেছনে ছিল মানুষ', factsNote:'OHCHR-এর হিসাব ১ জুলাই–১৫ আগস্ট ২০২৪ সময়কালের; এটি একটি অনুমান, চূড়ান্ত নামভিত্তিক তালিকা নয়।',
    facts:[
      {n:'১,৪০০ পর্যন্ত',label:'মানুষ নিহত হয়ে থাকতে পারেন',note:'OHCHR-এর বিশ্বাসযোগ্য উৎসভিত্তিক অনুমান; অধিকাংশ নিহত ও আহত নিরাপত্তা বাহিনীর গুলিতে।',s:1},
      {n:'১২–১৩%',label:'নিহতদের মধ্যে শিশু',note:'OHCHR-এর আনুমানিক অনুপাত—প্রায় ১৮০ শিশু পর্যন্ত।',s:1},
      {n:'১১,৭০০+',label:'আটক',note:'নিরাপত্তা সংস্থাগুলোর দেওয়া তথ্য উদ্ধৃত করে OHCHR-এর প্রতিবেদন।',s:1},
      {n:'১০,০০০+',label:'জুলাইয়েই গ্রেপ্তার',note:'২ আগস্ট ২০২৪-এ Amnesty International-এর তৎকালীন হিসাব।',s:5}
    ],
    timelineKicker:'পূর্ণ সময়রেখা', timelineTitle:'দাবি থেকে অভ্যুত্থান', timelineIntro:'প্রতিটি বাঁক আগের দিনের ক্ষোভ, সাহস ও আত্মত্যাগ বহন করেছে। নিচের সময়রেখা প্রধান ঘটনাগুলোর সংক্ষিপ্ত, উৎস-সংযুক্ত মানচিত্র।',
    timeline:[
      {date:'৫ জুন ২০২৪',tag:'তাৎক্ষণিক সূত্রপাত',title:'হাইকোর্টের রায়ে কোটা পুনর্বহাল',text:'২০১৮ সালের কোটা বাতিলের পরিপত্র অবৈধ ঘোষণা করে মুক্তিযোদ্ধা পরিবারের সন্তান–নাতিদের জন্য ৩০ শতাংশ কোটা কার্যত পুনর্বহাল করা হয়। বিভিন্ন বিশ্ববিদ্যালয়ে প্রতিবাদ শুরু হয়।',src:[1,4,6]},
      {date:'১–৬ জুলাই',tag:'সংগঠিত আন্দোলন',title:'বৈষম্যবিরোধী ছাত্র আন্দোলন ও বাংলা ব্লকেড',text:'শিক্ষার্থীরা নতুন ব্যানারে সংগঠিত হন; ঢাকা থেকে পাবলিক ও প্রাইভেট বিশ্ববিদ্যালয়, জেলা শহর ও মহাসড়কে আন্দোলন ছড়িয়ে পড়ে। ৭ জুলাই থেকে “বাংলা ব্লকেড”-এর ডাক আসে।',src:[2,6]},
      {date:'৭–১১ জুলাই',tag:'দেশব্যাপী বিস্তার',title:'রাস্তা, রেল ও ক্যাম্পাসে এক দাবি',text:'ঢাকার গুরুত্বপূর্ণ মোড় এবং দেশের বিভিন্ন সড়ক–রেলপথ অবরোধ হয়। আদালতের স্থগিতাদেশ এলেও শিক্ষার্থীরা নির্বাহী ও আইনগতভাবে টেকসই সংস্কারের নিশ্চয়তা চেয়ে কর্মসূচি চালিয়ে যান।',src:[4,6]},
      {date:'১৪ জুলাই',tag:'রাজনৈতিক বাঁক',title:'“রাজাকার” মন্তব্যে ক্ষোভের বিস্ফোরণ',text:'শেখ হাসিনার সংবাদ সম্মেলনের একটি মন্তব্যকে আন্দোলনকারীরা অপমান হিসেবে দেখেন। রাতে ক্যাম্পাসগুলোতে প্রতিবাদী স্লোগান ছড়িয়ে পড়ে এবং সংঘাতের ঝুঁকি দ্রুত বাড়ে।',src:[1,6],breaking:true},
      {date:'১৫ জুলাই',tag:'দলীয় হামলা',title:'ঢাকা বিশ্ববিদ্যালয় ও হাসপাতালে আক্রমণ',text:'OHCHR ও সংবাদ প্রতিবেদনে আওয়ামী লীগ-সংশ্লিষ্ট ছাত্র ও যুব সংগঠনের সদস্যদের শান্তিপূর্ণ আন্দোলনকারীদের ওপর হামলার বর্ণনা রয়েছে; আহতদের ঢাকা মেডিকেল কলেজ হাসপাতালেও আক্রমণ করা হয়।',src:[1,4,6],breaking:true},
      {date:'১৬ জুলাই',tag:'ভয় ভাঙার দিন',title:'আবু সাঈদের হত্যাকাণ্ড দেশকে নাড়িয়ে দেয়',text:'রংপুরে নিরস্ত্র শিক্ষার্থী আবু সাঈদ পুলিশের গুলিতে নিহত হন। দৃশ্যটি ছড়িয়ে পড়লে তিনি রাষ্ট্রীয় সহিংসতার বিরুদ্ধে প্রতিরোধের প্রতীক হয়ে ওঠেন; একই দিনে বিভিন্ন জেলায় অন্তত ছয়জন নিহতের খবর আসে।',src:[1,2,6],breaking:true},
      {date:'১৭–১৮ জুলাই',tag:'শাটডাউন ও অন্ধকার',title:'দেশব্যাপী কমপ্লিট শাটডাউন; ইন্টারনেট বিচ্ছিন্ন',text:'গায়েবানা জানাজায় পুলিশি হামলার পর “কমপ্লিট শাটডাউন” ডাকা হয়। ১৮ জুলাই বহু জেলায় প্রাণহানি ও সংঘর্ষের মধ্যে মোবাইল ও পরে ব্রডব্যান্ড ইন্টারনেট বন্ধ করে বাংলাদেশকে কার্যত বিশ্ব থেকে বিচ্ছিন্ন করা হয়।',src:[1,2,6],breaking:true},
      {date:'১৯–২০ জুলাই',tag:'কারফিউ ও প্রাণঘাতী বলপ্রয়োগ',title:'নয় দফা, কারফিউ, সেনা মোতায়েন',text:'গুলিবর্ষণ ও সংঘর্ষে বহু মানুষ নিহত হন। সমন্বয়কেরা বিচার, ক্ষমা ও দায়ীদের অপসারণসহ নয় দফা দেন। সরকার দেশব্যাপী কারফিউ জারি ও সেনা মোতায়েন করে; ঢাকার বিভিন্ন এলাকায় প্রাণঘাতী বলপ্রয়োগ অব্যাহত থাকে।',src:[1,2,6],breaking:true},
      {date:'২০–২৩ জুলাই',tag:'অপহরণ–নির্যাতনের অভিযোগ',title:'নাহিদ ইসলামকে তুলে নেওয়া; কোটা পরিপত্র জারি',text:'সমন্বয়ক নাহিদ ইসলামকে সাদা পোশাকধারীরা তুলে নিয়ে নির্যাতন করেছে—এমন অভিযোগ তিনি মুক্তির পর জানান। ২১ জুলাই আদালত কোটা ৭ শতাংশে নামায় এবং ২৩ জুলাই সরকার পরিপত্র দেয়; কিন্তু তখন আন্দোলনের কেন্দ্রে ছিল হত্যার বিচার।',src:[1,2,6],breaking:true},
      {date:'২৪–২৮ জুলাই',tag:'গণগ্রেপ্তার',title:'ব্লক রেইড, ডিবি হেফাজত ও জোরপূর্বক বিবৃতি',text:'হাজারো মানুষকে গ্রেপ্তার, অজ্ঞাতনামা আসামি করে মামলা এবং বাড়ি–হাসপাতাল থেকে সমন্বয়কদের তুলে নেওয়ার ঘটনা ঘটে। ডিবি হেফাজতে ছয় সমন্বয়কের আন্দোলন প্রত্যাহারের বিবৃতিকে অন্য সংগঠকেরা জোরপূর্বক বলে প্রত্যাখ্যান করেন।',src:[1,5,6],breaking:true},
      {date:'২৯–৩১ জুলাই',tag:'প্রতিরোধের প্রত্যাবর্তন',title:'লাল প্রোফাইল, March for Justice',text:'শিক্ষার্থী, শিক্ষক, অভিভাবক, আইনজীবী, শিল্পী ও নাগরিক সমাজ আবার প্রকাশ্যে দাঁড়ান। রাষ্ট্রীয় শোক প্রত্যাখ্যান করে সামাজিক যোগাযোগমাধ্যম লাল হয়ে ওঠে; “March for Justice” কর্মসূচিতে বাধা ও বলপ্রয়োগের মধ্যেও প্রতিবাদ চলতে থাকে।',src:[2,6,7]},
      {date:'১–২ আগস্ট',tag:'৩২–৩৩ জুলাই',title:'সমন্বয়কদের মুক্তি ও দ্রোহযাত্রা',text:'ছয় সমন্বয়ক ডিবি হেফাজত থেকে মুক্ত হন। ২ আগস্ট শিক্ষার্থী, শিক্ষক, অভিভাবক, চিকিৎসক, শিল্পী ও নাগরিকেরা জাতীয় প্রেস ক্লাব থেকে শহীদ মিনার পর্যন্ত দ্রোহযাত্রায় অংশ নিয়ে হত্যার বিচার ও দমন বন্ধের দাবি জানান।',src:[3,5,6]},
      {date:'৩ আগস্ট',tag:'এক দফা',title:'শহীদ মিনার থেকে সরকারের পদত্যাগ দাবি',text:'বৃষ্টির মধ্যেও বিপুল জনসমাবেশে নাহিদ ইসলাম শেখ হাসিনা ও মন্ত্রিসভার পদত্যাগের এক দফা ঘোষণা করেন। কোটা সংস্কারের আন্দোলন স্পষ্টভাবে সর্বজনীন রাজনৈতিক অভ্যুত্থানে রূপ নেয়।',src:[1,6],breaking:true},
      {date:'৪ আগস্ট',tag:'অসহযোগ',title:'অভ্যুত্থানের সবচেয়ে প্রাণঘাতী দিন',text:'সর্বাত্মক অসহযোগে দেশজুড়ে আন্দোলনকারী, পুলিশ ও আওয়ামী লীগ সমর্থকদের সংঘর্ষ হয়। সংবাদমাধ্যমের প্রাথমিক হিসাবে অন্তত ৯৩ জন নিহত হন। পরদিন “March to Dhaka” এগিয়ে আনার ঘোষণা আসে।',src:[1,6],breaking:true},
      {date:'৫ আগস্ট',tag:'৩৬ জুলাই',title:'কারফিউ ভেঙে ঢাকামুখী জনতা; শেখ হাসিনার পদত্যাগ',text:'হাজারো মানুষ কারফিউ অমান্য করে রাজধানীমুখী হন। দুপুরে শেখ হাসিনা পদত্যাগ করে দেশ ছাড়েন। মানুষ রাস্তায় বিজয় উদ্‌যাপন করে; একই সময়ে বিভিন্ন স্থানে প্রতিশোধমূলক হত্যা, অগ্নিসংযোগ ও সংখ্যালঘুদের ওপর হামলার ঘটনাও ঘটে।',src:[1,6,12],breaking:true},
      {date:'৫ আগস্টের পর',tag:'ন্যায়বিচারের পরীক্ষা',title:'রাষ্ট্র পরিবর্তনের দীর্ঘ কাজ শুরু',text:'অন্তর্বর্তী সরকার, তদন্ত ও সংস্কারের প্রক্রিয়া শুরু হয়। OHCHR সকল পক্ষের হত্যাকাণ্ড, নির্যাতন, প্রতিশোধমূলক সহিংসতা ও সংখ্যালঘুদের ওপর হামলার স্বাধীন তদন্ত, ভুক্তভোগীকেন্দ্রিক বিচার এবং নিরাপত্তা খাত সংস্কারের আহ্বান জানায়।',src:[1,12]}
    ],
    evidenceKicker:'OHCHR fact-finding · ২০২৫', evidenceTitle:'এটি কেবল “সংঘর্ষ” ছিল না', finding:'জাতিসংঘের মানবাধিকার দপ্তর বলেছে, সাবেক সরকার ও তার নিরাপত্তা–গোয়েন্দা কাঠামো, এবং আওয়ামী লীগের সঙ্গে সংশ্লিষ্ট সহিংস উপাদানগুলো বিক্ষোভ দমনে পদ্ধতিগতভাবে গুরুতর মানবাধিকার লঙ্ঘনে জড়িত ছিল—এমন বিশ্বাসের যৌক্তিক ভিত্তি রয়েছে। রাজনৈতিক নেতৃত্ব ও জ্যেষ্ঠ নিরাপত্তা কর্মকর্তাদের জ্ঞান, সমন্বয় ও নির্দেশনায় বিচারবহির্ভূত হত্যা, নির্বিচার গ্রেপ্তার এবং নির্যাতন সংঘটিত হয়েছে বলেও প্রতিবেদনে উল্লেখ করা হয়।', findingAttribution:'— OHCHR Fact-Finding Report, ১২ ফেব্রুয়ারি ২০২৫ (সারসংক্ষেপিত অনুবাদ)', openReport:'পূর্ণ প্রতিবেদন খুলুন ↗',
    violations:[['প্রাণঘাতী বলপ্রয়োগ','নিরস্ত্র আন্দোলনকারীকে কাছ থেকে গুলি এবং সামরিক রাইফেল ও ধাতব পেলেট ব্যবহারের ঘটনা OHCHR নথিভুক্ত করেছে।'],['নির্বিচার আটক','ব্লক রেইড, বিপুল অজ্ঞাতনামা আসামি এবং শিশু ও পথচারীসহ হাজারো মানুষকে আটক করা হয়।'],['নির্যাতন ও গুম','সমন্বয়ক ও আন্দোলনকারীদের গোপন স্থানে নেওয়া, মারধর, চোখ বাঁধা এবং জোরপূর্বক বিবৃতির অভিযোগ নথিভুক্ত হয়েছে।'],['তথ্য অবরোধ','ইন্টারনেট বন্ধ, সামাজিক যোগাযোগমাধ্যম অবরোধ ও সংবাদপ্রবাহ নিয়ন্ত্রণ চিকিৎসা, নথিকরণ ও জননিরাপত্তা ব্যাহত করে।']],
    photoKicker:'চারটি দলিল · চারটি অনুভব', photoTitle:'প্রতিরোধের দৃশ্যস্মৃতি', photoIntro:'এই আলোকচিত্রগুলো বেদনা, শপথ, এক দফা ও বিজয়ের ভিন্ন মুহূর্ত ধারণ করে। প্রতিটি ছবির পরিচিত উৎস বা আলোকচিত্রী উল্লেখ করা হয়েছে।',
    photos:[
      {src:'https://ncpdagermany.de/img/july/selected/august-05-parliament-afp.webp',alt:'৫ আগস্ট ২০২৪ জাতীয় সংসদ ভবনে জনতা',title:'৩৬ জুলাই · জনতার বিজয়',credit:'৫ আগস্ট ২০২৪ · AFP আলোকচিত্র'},
      {src:'https://ncpdagermany.de/img/july/selected/august-02-salute-orchid-chakma.webp',alt:'পতাকার পাশে স্যালুটরত আন্দোলনকারী',title:'পতাকার সামনে শপথ',credit:'২ আগস্ট ২০২৪ · ছবি: অর্কিড চাকমা'},
      {src:'https://ncpdagermany.de/img/july/selected/august-03-march-palash-khan.webp',alt:'এক দফা লেখা প্ল্যাকার্ডসহ জনতা',title:'এক দফা · এক জনতা',credit:'৩ আগস্ট ২০২৪ · ছবি: পলাশ খান'},
      {src:'https://ncpdagermany.de/img/july/selected/july-resistance-art.webp',alt:'জুলাইয়ের প্রতিরোধী শিল্পকর্ম',title:'শিল্পেও প্রতিরোধ',credit:'আন্দোলনকালীন শিল্পকর্ম · শিল্পী অজ্ঞাত'}
    ],
    peopleKicker:'যে শক্তিগুলো ইতিহাস বদলেছে', peopleTitle:'একটি প্রজন্ম, একটি জনতা, একটি বিশ্বব্যাপী সংহতি',
    people:[['তরুণ ও শিক্ষার্থী','ক্যাম্পাসভিত্তিক নেটওয়ার্ক, বিকেন্দ্রীভূত সমন্বয় এবং দ্রুত সিদ্ধান্ত আন্দোলনের ভিত্তি তৈরি করে। সরকারি–বেসরকারি বিশ্ববিদ্যালয়, কলেজ ও মাদ্রাসার শিক্ষার্থীরা ভিন্ন বিভাজন অতিক্রম করেন।','টাইমলাইন পড়ুন','#timeline'],['নারী ও সাধারণ মানুষ','নারী শিক্ষার্থীরা শুরু থেকেই সামনে ছিলেন। পরে শ্রমিক, অভিভাবক, শিক্ষক, চিকিৎসক, আইনজীবী, শিল্পী, রিকশাচালক ও দোকানদাররা আন্দোলনকে ছাত্রবিক্ষোভ থেকে গণঅভ্যুত্থানে পরিণত করেন।','নারীদের ভূমিকা ↗','https://www.thedailystar.net/news/bangladesh/news/inside-july-uprising-women-led-nation-followed-3950221'],['ডিজিটাল ও প্রবাসী প্রতিরোধ','ইন্টারনেট বন্ধের মধ্যেও ভিডিও, গ্রাফিতি, গান, অনুবাদ ও আন্তর্জাতিক প্রচার সত্যকে সীমান্তের বাইরে পৌঁছে দেয়। প্রবাসীদের সমাবেশ ও অর্থনৈতিক অসহযোগ চাপের নতুন ক্ষেত্র তৈরি করে।','প্রবাসীর ভূমিকা ↗',SOURCES[8].url]],
    ncpKicker:'জুলাই থেকে নতুন রাজনৈতিক যাত্রা', ncpTitle:'আন্দোলনের কয়েকজন সংগঠক পরে NCP-র প্রতিষ্ঠাতা নেতৃত্বে', ncpClarification:'<b>ঐতিহাসিকভাবে গুরুত্বপূর্ণ:</b> National Citizen Party (NCP) জুলাই ২০২৪-এ অস্তিত্বশীল ছিল না। দলটি প্রতিষ্ঠিত হয় ২৮ ফেব্রুয়ারি ২০২৫। তাই জুলাইয়ে তাদের ভূমিকা NCP নেতা হিসেবে নয়—বৈষম্যবিরোধী ছাত্র আন্দোলনের সমন্বয়ক ও সংগঠক হিসেবে।', ncpText:'নাহিদ ইসলাম, আখতার হোসেন, হাসনাত আবদুল্লাহ, সারজিস আলমসহ আন্দোলনে পরিচিত হয়ে ওঠা কয়েকজন তরুণ পরে NCP-র প্রতিষ্ঠাতা নেতৃত্বে যুক্ত হন। ৩ আগস্ট শহীদ মিনারে নাহিদ ইসলামের এক দফা ঘোষণা এবং সমন্বয়কদের ওপর আটক–নির্যাতনের অভিজ্ঞতা এই রাজনৈতিক প্রজন্মের ইতিহাসে গুরুত্বপূর্ণ। তবে জুলাই ছিল বহু দল, মত, শ্রেণি ও পরিচয়ের ছাত্র–জনতার সম্মিলিত অভ্যুত্থান—কোনো একক পরবর্তী দলের সম্পত্তি নয়।', ncpSourceOne:'AP · NCP প্রতিষ্ঠার প্রেক্ষাপট ↗',ncpSourceTwo:'BSS · প্রতিষ্ঠাকালীন নেতৃত্ব ↗',
    diasporaKicker:'সীমানার বাইরে প্রতিরোধ',diasporaTitle:'ইন্টারনেট বন্ধ ছিল, সংহতি থামেনি',diasporaText:'বাংলাদেশের সঙ্গে যোগাযোগ বিচ্ছিন্ন হওয়ার সময় প্রবাসীরা তথ্য অনুবাদ ও প্রচার, আন্তর্জাতিক সংবাদমাধ্যম ও মানবাধিকার সংগঠনের দৃষ্টি আকর্ষণ, দূতাবাসের সামনে বিক্ষোভ এবং রেমিট্যান্স বয়কটের মাধ্যমে চাপ তৈরি করেন। জার্মানির ফ্রাঙ্কফুর্ট ও ডার্মস্টাডটসহ বিভিন্ন শহরের কর্মসূচি এই বৈশ্বিক সংহতির অংশ ছিল।',diasporaClarification:'<b>স্পষ্টীকরণ:</b> এটি ২০২৪ সালের বৃহত্তর বাংলাদেশি প্রবাসী সমাজের ভূমিকা। পরবর্তীতে গড়ে ওঠা NCP Diaspora Alliance Germany সেই ইতিহাসকে ধারণ করে, কিন্তু জুলাইয়ের সব প্রবাসী কার্যক্রমের সংগঠক হিসেবে নিজেকে দাবি করে না।',diasporaSource:'প্রবাসীদের ভূমিকার প্রতিবেদন পড়ুন ↗',
    legacyKicker:'জুলাইয়ের অসমাপ্ত অঙ্গীকার',legacyTitle:'বিজয় মানে শুধু ক্ষমতার পরিবর্তন নয়',pledges:[['সত্য ও ন্যায়বিচার','সব হত্যাকাণ্ড ও নির্যাতনের স্বাধীন, নিরপেক্ষ ও ভুক্তভোগীকেন্দ্রিক তদন্ত।'],['প্রাতিষ্ঠানিক জবাবদিহি','পুলিশ, গোয়েন্দা সংস্থা, বিচার ও নির্বাচনব্যবস্থাকে দলীয় নিয়ন্ত্রণমুক্ত করা।'],['সমান নাগরিক মর্যাদা','নারী, সংখ্যালঘু, আদিবাসী, প্রতিবন্ধী ও ভিন্নমতের মানুষের নিরাপত্তা ও সমঅধিকার।'],['স্মৃতি ও শিক্ষা','শহিদ–আহতদের নাম, সাক্ষ্য ও দলিল সংরক্ষণ; ভুল তথ্য নয়, যাচাইকৃত ইতিহাস শেখানো।']],
    sourcesKicker:'নিজে যাচাই করুন',sourcesTitle:'প্রাথমিক প্রতিবেদন ও পাঠাগার',sourcesIntro:'এই পাতা একটি প্রবেশদ্বার। পূর্ণ সাক্ষ্য, ভুক্তভোগীর তালিকা, আলোকচিত্র ও অনুসন্ধানী প্রতিবেদন জানতে মূল উৎসগুলো পড়ুন।',
    sourceTitles:['জুলাই–আগস্ট ২০২৪-এর বিক্ষোভকেন্দ্রিক মানবাধিকার লঙ্ঘন ও নিপীড়ন: অনুসন্ধানী প্রতিবেদন','বাংলাদেশের সাম্প্রতিক বিক্ষোভ ও অস্থিরতার প্রাথমিক বিশ্লেষণ','বাংলাদেশের সহিংসতায় অন্তত ৩২ শিশু নিহত','বাংলাদেশের কোটা সংস্কার আন্দোলনে কী ঘটেছিল?','হাজারো আন্দোলনকারীকে নির্বিচারে গ্রেপ্তার','কোটা থেকে রাষ্ট্র সংস্কার—জুলাই গণঅভ্যুত্থানের সময়রেখা','৩৬ দিনের জুলাই—প্রতিবেদন, সাক্ষ্য ও অনুসন্ধান','জুলাই গণঅভ্যুত্থানের ছবি ও দলিলের উন্মুক্ত আর্কাইভ','বিদেশ থেকে বাংলাদেশি প্রবাসীরা যেভাবে জুলাই আন্দোলনের পাশে দাঁড়িয়েছিলেন','অভ্যুত্থানের ছাত্রনেতাদের National Citizen Party গঠন','National Citizen Party-র আনুষ্ঠানিক আত্মপ্রকাশ','রাজনৈতিক পরিবর্তনের পর ন্যায়বিচার ও সুরক্ষার আহ্বান'],
    sourceMeta:['জাতিসংঘ মানবাধিকার দপ্তর · ১২ ফেব্রুয়ারি ২০২৫','জাতিসংঘ মানবাধিকার দপ্তর · ১৬ আগস্ট ২০২৪','UNICEF দক্ষিণ এশিয়া · ২ আগস্ট ২০২৪','Amnesty International · জুলাই ২০২৪','Amnesty International · ২ আগস্ট ২০২৪','সংযুক্ত সংবাদপ্রতিবেদনসহ ধারাবাহিকতা · ২০১৮–৫ আগস্ট ২০২৪','মাল্টিমিডিয়া আর্কাইভ · ২০২৬','বাংলাদেশ সরকারের উন্মুক্ত আর্কাইভ','জার্মানিসহ প্রবাসীদের ভূমিকা · ৫ সেপ্টেম্বর ২০২৪','Associated Press · ২৮ ফেব্রুয়ারি ২০২৫','বাংলাদেশ সংবাদ সংস্থা · ২৮ ফেব্রুয়ারি ২০২৫','জাতিসংঘ মহাসচিব · ৫ আগস্ট ২০২৪'],
    closingKicker:'স্মৃতি থেকে দায়িত্ব',closingTitle:'যাদের রক্তে ভয় ভেঙেছিল,<br>তাদের স্বপ্নে রাষ্ট্র গড়তে হবে।',closingText:'জুলাইকে স্মরণ করা মানে প্রতিহিংসা নয়—সত্য প্রতিষ্ঠা, সব হত্যার নিরপেক্ষ বিচার, মানবিক মর্যাদা এবং এমন প্রতিষ্ঠান গড়া, যেখানে কোনো সরকার আর নাগরিকের কণ্ঠকে গুলি, আটক বা ইন্টারনেট বন্ধ করে স্তব্ধ করতে না পারে।',shareArchive:'এই আর্কাইভ শেয়ার করুন',footerNote:'নাগরিক শিক্ষা ও ঐতিহাসিক স্মৃতি সংরক্ষণের উদ্যোগ',mainSite:'মূল ওয়েবসাইট',sourceNav:'উৎস',backTop:'উপরে ফিরুন ↑',copied:'লিংক কপি হয়েছে।'
  };

  const en = {
    archiveLabel:'July Knowledge Archive',share:'Share',heroKicker:'Bangladesh · 5 June—5 August 2024',heroTitle:'A people’s uprising<br>against silence',heroLead:'From a legitimate demand for quota reform to a nationwide call for state reform—the record of 36 days that transformed Bangladesh through youth courage, public solidarity and a brutal crackdown.',explore:'Explore the timeline',readEvidence:'Read the UN findings',scroll:'Enter the history',
    methodKicker:'Editorial standard',methodTitle:'Memory, grounded in evidence',methodText:'This archive synthesises findings from the UN Human Rights Office, UNICEF, Amnesty International, news reporting and open public archives. Casualty figures differ by source and reporting date, so every number is presented with its source and time period.',balanceText:'Justice must also cover violence by protesters and revenge attacks during and after 5 August—including killings and attacks against police, Awami League members, and religious and ethnic minorities.',
    factsKicker:'Documented scale',factsTitle:'Behind every number was a person',factsNote:'The OHCHR estimate covers 1 July–15 August 2024. It is an estimate, not a final verified list of names.',facts:[{n:'Up to 1,400',label:'people may have been killed',note:'OHCHR estimate based on credible sources; the vast majority of killed and injured were shot by security forces.',s:1},{n:'12–13%',label:'of those killed were children',note:'OHCHR’s estimated proportion—potentially as many as about 180 children.',s:1},{n:'11,700+',label:'people detained',note:'OHCHR, citing information provided by the security services.',s:1},{n:'10,000+',label:'arrests in July alone',note:'Amnesty International’s contemporary figure on 2 August 2024.',s:5}],
    timelineKicker:'Full chronology',timelineTitle:'From a demand to an uprising',timelineIntro:'Every turning point carried the anger, courage and sacrifice of the day before it. This is a sourced map of the defining events.',
    timeline:[
      {date:'5 June 2024',tag:'Immediate trigger',title:'High Court restores the quota',text:'The court invalidated the 2018 circular that abolished quotas, effectively restoring the 30% allocation for children and grandchildren of freedom fighters. Protests began across several universities.',src:[1,4,6]},
      {date:'1–6 July',tag:'A movement organises',title:'Students Against Discrimination and Bangla Blockade',text:'Students organised under a new banner. Protests spread from Dhaka to public and private universities, district towns and highways; organisers called the “Bangla Blockade” from 7 July.',src:[2,6]},
      {date:'7–11 July',tag:'Nationwide expansion',title:'One demand across roads, rails and campuses',text:'Major junctions in Dhaka and transport routes nationwide were blocked. Even after an appellate stay, students continued to demand durable executive and legislative reform.',src:[4,6]},
      {date:'14 July',tag:'Political turning point',title:'The “razakar” remark ignites outrage',text:'Protesters interpreted a remark by Sheikh Hasina at a press conference as an insult. Protest slogans swept campuses overnight and the risk of confrontation escalated.',src:[1,6],breaking:true},
      {date:'15 July',tag:'Party-linked attacks',title:'Attacks at Dhaka University and a hospital',text:'OHCHR and news reports describe members of Awami League-affiliated student and youth groups attacking peaceful protesters; injured demonstrators were also attacked around Dhaka Medical College Hospital.',src:[1,4,6],breaking:true},
      {date:'16 July',tag:'The day fear broke',title:'The killing of Abu Sayed shakes the country',text:'Police shot and killed unarmed student Abu Sayed in Rangpur. Widely shared footage made him a symbol of resistance to state violence; at least six deaths were reported nationwide that day.',src:[1,2,6],breaking:true},
      {date:'17–18 July',tag:'Shutdown and darkness',title:'Complete Shutdown; the internet goes dark',text:'After police action at memorial prayers, organisers called a “Complete Shutdown.” Amid deaths and clashes across many districts on 18 July, mobile and then broadband internet were cut, isolating Bangladesh.',src:[1,2,6],breaking:true},
      {date:'19–20 July',tag:'Curfew and lethal force',title:'Nine demands, curfew and army deployment',text:'Many were killed amid gunfire and clashes. Coordinators issued nine demands for justice and accountability. The government imposed a nationwide curfew and deployed the army as lethal force continued.',src:[1,2,6],breaking:true},
      {date:'20–23 July',tag:'Abduction and torture alleged',title:'Nahid Islam taken; quota circular issued',text:'Coordinator Nahid Islam said plainclothes men abducted and tortured him. The court reduced quotas to 7% and the government issued a circular, but justice for the killings had become central to the movement.',src:[1,2,6],breaking:true},
      {date:'24–28 July',tag:'Mass arrests',title:'Block raids, DB custody and a coerced statement',text:'Thousands were arrested, cases named vast numbers of unidentified accused, and coordinators were taken from homes and hospitals. Organisers outside custody rejected a withdrawal statement by six detained coordinators as coerced.',src:[1,5,6],breaking:true},
      {date:'29–31 July',tag:'Resistance returns',title:'Red profiles and the March for Justice',text:'Students, teachers, parents, lawyers, artists and civil society returned to public protest. Social media turned red in rejection of official mourning; the March for Justice continued despite obstruction and force.',src:[2,6,7]},
      {date:'1–2 August',tag:'32–33 July',title:'Coordinators freed; the March of Defiance',text:'Six coordinators were released from DB custody. On 2 August, a broad public march from the National Press Club to Shaheed Minar demanded justice for the killings and an end to repression.',src:[3,5,6]},
      {date:'3 August',tag:'One demand',title:'Shaheed Minar calls for the government to resign',text:'Before a huge gathering, Nahid Islam announced the one-point demand for Sheikh Hasina and the cabinet to resign. The quota movement had visibly become a nationwide political uprising.',src:[1,6],breaking:true},
      {date:'4 August',tag:'Non-cooperation',title:'The uprising’s deadliest day',text:'Nationwide non-cooperation brought violent clashes among protesters, police and Awami League supporters. Contemporary media reported at least 93 deaths. Organisers advanced the March to Dhaka to the next day.',src:[1,6],breaking:true},
      {date:'5 August',tag:'36 July',title:'Crowds defy curfew; Sheikh Hasina resigns',text:'Thousands moved towards Dhaka in defiance of curfew. Sheikh Hasina resigned and left the country that afternoon. Crowds celebrated, while revenge killings, arson and attacks on minorities were also reported in several places.',src:[1,6,12],breaking:true},
      {date:'After 5 August',tag:'The test of justice',title:'The long work of changing the state begins',text:'An interim government, investigations and reform processes followed. OHCHR called for independent investigations into abuses by all sides, victim-centred justice and deep reform of the security sector.',src:[1,12]}
    ],
    evidenceKicker:'OHCHR fact-finding · 2025',evidenceTitle:'This was not merely “clashes”',finding:'The UN Human Rights Office found reasonable grounds to believe that the former government and its security and intelligence apparatus, together with violent elements associated with the Awami League, systematically committed serious human-rights violations to suppress the protests. The report said extrajudicial killings, arbitrary arrests and torture occurred with the knowledge, coordination and direction of political leaders and senior security officials.',findingAttribution:'— OHCHR Fact-Finding Report, 12 February 2025 (condensed)',openReport:'Open the full report ↗',violations:[['Lethal force','OHCHR documented point-blank shootings of unarmed protesters and the use of military rifles and metal pellets.'],['Arbitrary detention','Block raids and cases with vast numbers of unnamed accused swept up thousands, including children and bystanders.'],['Torture and disappearance','Coordinators and protesters reported being taken to secret locations, blindfolded, beaten and pressed into statements.'],['Information blackout','Internet and platform shutdowns obstructed medical response, documentation, public safety and independent reporting.']],
    photoKicker:'Four records · four emotions',photoTitle:'A visual memory of resistance',photoIntro:'These photographs hold distinct moments of pain, resolve, the one-point demand and victory. Every known photographer or source is credited.',photos:[{src:'https://ncpdagermany.de/img/july/selected/august-05-parliament-afp.webp',alt:'Crowds at the parliament building on 5 August 2024',title:'36 July · a people’s victory',credit:'5 August 2024 · AFP photograph'},{src:'https://ncpdagermany.de/img/july/selected/august-02-salute-orchid-chakma.webp',alt:'A protester salutes beside the flag',title:'A pledge before the flag',credit:'2 August 2024 · Photo: Orchid Chakma'},{src:'https://ncpdagermany.de/img/july/selected/august-03-march-palash-khan.webp',alt:'Crowd with a one-point placard',title:'One demand · one people',credit:'3 August 2024 · Photo: Palash Khan'},{src:'https://ncpdagermany.de/img/july/selected/july-resistance-art.webp',alt:'Resistance art from the July uprising',title:'Resistance through art',credit:'Protest-era artwork · artist unknown'}],
    peopleKicker:'The forces that changed history',peopleTitle:'A generation, a people, a global solidarity',people:[['Youth and students','Campus networks, decentralised coordination and fast decisions formed the movement’s foundation. Students from public and private universities, colleges and madrasas crossed old divisions.','Read the timeline','#timeline'],['Women and ordinary citizens','Women students were at the front from the start. Workers, parents, teachers, doctors, lawyers, artists, rickshaw drivers and shopkeepers then transformed a student protest into a mass uprising.','Women in the uprising ↗','https://www.thedailystar.net/news/bangladesh/news/inside-july-uprising-women-led-nation-followed-3950221'],['Digital and diaspora resistance','Despite the blackout, video, graffiti, music, translation and international advocacy carried evidence across borders. Diaspora protests and economic non-cooperation created another field of pressure.','Diaspora role ↗',SOURCES[8].url]],
    ncpKicker:'A new political journey after July',ncpTitle:'Some movement organisers later became NCP’s founding leaders',ncpClarification:'<b>Historical clarification:</b> The National Citizen Party (NCP) did not exist in July 2024. It was founded on 28 February 2025. Their July roles were therefore as coordinators and organisers of Students Against Discrimination—not as NCP leaders.',ncpText:'Nahid Islam, Akhtar Hossen, Hasnat Abdullah and Sarjis Alam were among the young figures associated with the movement who later joined NCP’s founding leadership. Nahid’s one-point announcement on 3 August and the detention and alleged torture of coordinators are important in the history of this political generation. But July was a broad student–people’s uprising across parties, views, classes and identities—not the property of any one party formed later.',ncpSourceOne:'AP · context of NCP’s launch ↗',ncpSourceTwo:'BSS · founding leadership ↗',
    diasporaKicker:'Resistance beyond borders',diasporaTitle:'The internet stopped; solidarity did not',diasporaText:'When communication with Bangladesh was severed, diaspora communities translated and circulated information, sought attention from international media and rights groups, protested outside missions and used a remittance boycott to create pressure. Demonstrations in Frankfurt, Darmstadt and other German cities formed part of that global solidarity.',diasporaClarification:'<b>Clarification:</b> This was the contribution of the wider Bangladeshi diaspora in 2024. NCP Diaspora Alliance Germany, formed later, carries that memory but does not claim to have organised every diaspora action during July.',diasporaSource:'Read the diaspora report ↗',
    legacyKicker:'July’s unfinished promise',legacyTitle:'Victory is more than a change of power',pledges:[['Truth and justice','Independent, impartial and victim-centred investigation of every killing and act of torture.'],['Institutional accountability','Free policing, intelligence, justice and elections from partisan capture.'],['Equal citizenship','Security and equal rights for women, minorities, Indigenous people, persons with disabilities and dissenters.'],['Memory and education','Preserve names, testimony and evidence; teach verified history, not disinformation.']],
    sourcesKicker:'Verify it yourself',sourcesTitle:'Primary reports and reading library',sourcesIntro:'This page is a gateway. Follow the original sources for full testimony, victim records, photography and investigations.',sourceTitles:SOURCES.map((source)=>source.title),sourceMeta:SOURCES.map((source)=>source.meta),closingKicker:'From memory to responsibility',closingTitle:'Fear broke through their blood;<br>the state must be built through their dreams.',closingText:'Remembering July is not a call for revenge. It means establishing truth, impartially judging every killing, protecting human dignity and building institutions no government can use to silence citizens with bullets, detention or an internet shutdown.',shareArchive:'Share this archive',footerNote:'An initiative for civic education and the preservation of historical memory',mainSite:'Main website',sourceNav:'Sources',backTop:'Back to top ↑',copied:'Link copied.'
  };

  const de = {
    archiveLabel:'Juli-Wissensarchiv',share:'Teilen',heroKicker:'Bangladesch · 5. Juni—5. August 2024',heroTitle:'Ein Volksaufstand<br>gegen das Schweigen',heroLead:'Von der berechtigten Forderung nach einer Quotenreform zum landesweiten Ruf nach Staatsreformen—die Dokumentation von 36 Tagen, in denen Mut, Solidarität und brutale Repression Bangladesch veränderten.',explore:'Chronologie ansehen',readEvidence:'UN-Ergebnisse lesen',scroll:'In die Geschichte eintreten',
    methodKicker:'Redaktioneller Standard',methodTitle:'Erinnerung auf Grundlage von Belegen',methodText:'Dieses Archiv bündelt Erkenntnisse des UN-Menschenrechtsbüros, von UNICEF, Amnesty International, Medien und öffentlichen Archiven. Opferzahlen unterscheiden sich je nach Quelle und Erhebungszeitpunkt; jede Zahl wird deshalb mit Quelle und Zeitraum angegeben.',balanceText:'Zur Gerechtigkeit gehört auch die Aufarbeitung von Gewalt durch Demonstrierende und Vergeltungsangriffen während und nach dem 5. August—einschließlich Angriffen auf Polizei, Mitglieder der Awami League sowie religiöse und ethnische Minderheiten.',
    factsKicker:'Dokumentiertes Ausmaß',factsTitle:'Hinter jeder Zahl stand ein Mensch',factsNote:'Die OHCHR-Schätzung umfasst den 1. Juli bis 15. August 2024. Sie ist keine endgültige, namentlich verifizierte Opferliste.',facts:[{n:'Bis zu 1.400',label:'Menschen könnten getötet worden sein',note:'OHCHR-Schätzung aus glaubwürdigen Quellen; die große Mehrheit der Getöteten und Verletzten wurde von Sicherheitskräften angeschossen.',s:1},{n:'12–13 %',label:'der Getöteten waren Kinder',note:'Geschätzter Anteil laut OHCHR—möglicherweise bis zu etwa 180 Kinder.',s:1},{n:'11.700+',label:'Menschen wurden inhaftiert',note:'OHCHR unter Berufung auf Angaben der Sicherheitsdienste.',s:1},{n:'10.000+',label:'Festnahmen allein im Juli',note:'Zeitgenössische Angabe von Amnesty International vom 2. August 2024.',s:5}],
    timelineKicker:'Vollständige Chronologie',timelineTitle:'Von einer Forderung zum Aufstand',timelineIntro:'Jede Wendung trug Wut, Mut und Opfer des Vortags in sich. Diese Chronologie fasst die entscheidenden Ereignisse mit Quellen zusammen.',
    timeline:[
      {date:'5. Juni 2024',tag:'Unmittelbarer Auslöser',title:'High Court stellt die Quote wieder her',text:'Das Gericht erklärte den Erlass von 2018 zur Abschaffung der Quoten für unwirksam und stellte damit faktisch die 30-Prozent-Quote für Nachkommen von Freiheitskämpfern wieder her. An mehreren Universitäten begann Protest.',src:[1,4,6]},
      {date:'1.–6. Juli',tag:'Die Bewegung organisiert sich',title:'Students Against Discrimination und Bangla Blockade',text:'Studierende organisierten sich unter einem neuen Namen. Von Dhaka aus breiteten sich Proteste auf staatliche und private Hochschulen, Bezirksstädte und Fernstraßen aus; ab 7. Juli wurde zur „Bangla Blockade“ aufgerufen.',src:[2,6]},
      {date:'7.–11. Juli',tag:'Landesweite Ausweitung',title:'Eine Forderung auf Straßen, Schienen und Campus',text:'Zentrale Kreuzungen in Dhaka sowie Verkehrswege im ganzen Land wurden blockiert. Trotz einer gerichtlichen Aussetzung verlangten Studierende eine dauerhafte gesetzliche Reform.',src:[4,6]},
      {date:'14. Juli',tag:'Politische Wendung',title:'Die „Razakar“-Bemerkung entfacht Empörung',text:'Demonstrierende verstanden eine Äußerung Sheikh Hasinas auf einer Pressekonferenz als Beleidigung. Über Nacht erfassten Protestparolen die Campus; das Konfrontationsrisiko stieg.',src:[1,6],breaking:true},
      {date:'15. Juli',tag:'Parteinahe Angriffe',title:'Angriffe an der Dhaka University und am Krankenhaus',text:'OHCHR und Medien beschreiben Angriffe von Mitgliedern Awami-League-naher Studenten- und Jugendorganisationen auf friedliche Demonstrierende; auch Verletzte am Dhaka Medical College Hospital wurden angegriffen.',src:[1,4,6],breaking:true},
      {date:'16. Juli',tag:'Der Tag, an dem die Angst brach',title:'Die Tötung Abu Sayeds erschüttert das Land',text:'Die Polizei erschoss in Rangpur den unbewaffneten Studenten Abu Sayed. Das verbreitete Video machte ihn zum Symbol gegen staatliche Gewalt; landesweit wurden an diesem Tag mindestens sechs Todesfälle gemeldet.',src:[1,2,6],breaking:true},
      {date:'17.–18. Juli',tag:'Stillstand und Dunkelheit',title:'Complete Shutdown; das Internet erlischt',text:'Nach Polizeigewalt bei Trauergebeten riefen Organisatoren zum „Complete Shutdown“ auf. Inmitten von Toten und Zusammenstößen wurden Mobil- und Breitbandinternet abgeschaltet und Bangladesch isoliert.',src:[1,2,6],breaking:true},
      {date:'19.–20. Juli',tag:'Ausgangssperre und tödliche Gewalt',title:'Neun Forderungen, Ausgangssperre, Armeeeinsatz',text:'Viele Menschen starben durch Schüsse und Zusammenstöße. Koordinatoren stellten neun Forderungen nach Gerechtigkeit. Die Regierung verhängte eine landesweite Ausgangssperre und setzte die Armee ein.',src:[1,2,6],breaking:true},
      {date:'20.–23. Juli',tag:'Entführung und Folter vorgeworfen',title:'Nahid Islam verschleppt; Quotenerlass veröffentlicht',text:'Koordinator Nahid Islam erklärte, Männer in Zivil hätten ihn entführt und gefoltert. Das Gericht senkte die Quote auf 7 Prozent und die Regierung erließ eine Regelung; inzwischen stand jedoch Gerechtigkeit für die Getöteten im Zentrum.',src:[1,2,6],breaking:true},
      {date:'24.–28. Juli',tag:'Massenfestnahmen',title:'Razzien, DB-Gewahrsam und erzwungene Erklärung',text:'Tausende wurden festgenommen, Verfahren nannten massenhaft unbekannte Beschuldigte und Koordinatoren wurden aus Wohnungen und Krankenhäusern geholt. Organisatoren in Freiheit bezeichneten die Rückzugserklärung sechs Inhaftierter als erzwungen.',src:[1,5,6],breaking:true},
      {date:'29.–31. Juli',tag:'Der Widerstand kehrt zurück',title:'Rote Profile und March for Justice',text:'Studierende, Lehrkräfte, Eltern, Juristen, Künstler und Zivilgesellschaft kehrten auf die Straße zurück. Soziale Medien färbten sich als Ablehnung der Staatstrauer rot; der March for Justice ging trotz Gewalt weiter.',src:[2,6,7]},
      {date:'1.–2. August',tag:'32.–33. Juli',title:'Koordinatoren frei; Marsch des Widerstands',text:'Sechs Koordinatoren wurden aus DB-Gewahrsam freigelassen. Am 2. August verlangte ein breiter Marsch vom National Press Club zum Shaheed Minar Gerechtigkeit und ein Ende der Repression.',src:[3,5,6]},
      {date:'3. August',tag:'Eine Forderung',title:'Shaheed Minar fordert den Rücktritt der Regierung',text:'Vor einer riesigen Versammlung verkündete Nahid Islam die Ein-Punkt-Forderung nach Rücktritt Sheikh Hasinas und des Kabinetts. Die Quotenbewegung war sichtbar zu einem landesweiten politischen Aufstand geworden.',src:[1,6],breaking:true},
      {date:'4. August',tag:'Nichtzusammenarbeit',title:'Der tödlichste Tag des Aufstands',text:'Die landesweite Nichtzusammenarbeit führte zu schweren Zusammenstößen zwischen Demonstrierenden, Polizei und Anhängern der Awami League. Medien meldeten zunächst mindestens 93 Tote. Der Marsch auf Dhaka wurde vorgezogen.',src:[1,6],breaking:true},
      {date:'5. August',tag:'36. Juli',title:'Menschen widersetzen sich der Sperre; Hasina tritt zurück',text:'Tausende zogen trotz Ausgangssperre nach Dhaka. Am Nachmittag trat Sheikh Hasina zurück und verließ das Land. Menschen feierten; zugleich wurden Vergeltungstötungen, Brandstiftung und Angriffe auf Minderheiten gemeldet.',src:[1,6,12],breaking:true},
      {date:'Nach dem 5. August',tag:'Die Bewährungsprobe der Gerechtigkeit',title:'Die lange Arbeit am Staat beginnt',text:'Eine Übergangsregierung, Ermittlungen und Reformprozesse folgten. OHCHR forderte unabhängige Untersuchungen aller Übergriffe, opferzentrierte Gerechtigkeit und eine tiefgreifende Reform des Sicherheitssektors.',src:[1,12]}
    ],
    evidenceKicker:'OHCHR Fact-Finding · 2025',evidenceTitle:'Dies waren nicht bloß „Zusammenstöße“',finding:'Das UN-Menschenrechtsbüro sah begründeten Anlass zu der Annahme, dass die frühere Regierung, ihr Sicherheits- und Geheimdienstapparat sowie gewalttätige, mit der Awami League verbundene Elemente systematisch schwere Menschenrechtsverletzungen zur Unterdrückung der Proteste begingen. Außergerichtliche Tötungen, willkürliche Festnahmen und Folter seien mit Wissen, Koordination und Leitung der politischen Führung und ranghoher Sicherheitsvertreter erfolgt.',findingAttribution:'— OHCHR Fact-Finding Report, 12. Februar 2025 (gekürzt)',openReport:'Vollständigen Bericht öffnen ↗',violations:[['Tödliche Gewalt','OHCHR dokumentierte Schüsse aus nächster Nähe auf Unbewaffnete sowie den Einsatz militärischer Gewehre und Metallpellets.'],['Willkürliche Inhaftierung','Razzien und Verfahren mit massenhaft unbekannten Beschuldigten erfassten Tausende, darunter Kinder und Unbeteiligte.'],['Folter und Verschwindenlassen','Koordinatoren und Demonstrierende berichteten von geheimen Orten, Augenbinden, Schlägen und erzwungenen Erklärungen.'],['Informationssperre','Internet- und Plattformabschaltungen behinderten medizinische Hilfe, Dokumentation, Sicherheit und unabhängige Berichte.']],
    photoKicker:'Vier Dokumente · vier Gefühle',photoTitle:'Visuelles Gedächtnis des Widerstands',photoIntro:'Die Fotos zeigen Schmerz, Entschlossenheit, die Ein-Punkt-Forderung und den Sieg. Bekannte Fotografen und Quellen sind angegeben.',photos:[{src:'https://ncpdagermany.de/img/july/selected/august-05-parliament-afp.webp',alt:'Menschen am Parlament am 5. August 2024',title:'36. Juli · Sieg der Bevölkerung',credit:'5. August 2024 · AFP-Fotografie'},{src:'https://ncpdagermany.de/img/july/selected/august-02-salute-orchid-chakma.webp',alt:'Demonstrant salutiert neben einer Flagge',title:'Ein Versprechen vor der Flagge',credit:'2. August 2024 · Foto: Orchid Chakma'},{src:'https://ncpdagermany.de/img/july/selected/august-03-march-palash-khan.webp',alt:'Menge mit Ein-Punkt-Plakat',title:'Eine Forderung · ein Volk',credit:'3. August 2024 · Foto: Palash Khan'},{src:'https://ncpdagermany.de/img/july/selected/july-resistance-art.webp',alt:'Widerstandskunst des Juli-Aufstands',title:'Widerstand durch Kunst',credit:'Kunst aus der Protestzeit · Künstler unbekannt'}],
    peopleKicker:'Kräfte, die Geschichte veränderten',peopleTitle:'Eine Generation, ein Volk, weltweite Solidarität',people:[['Jugend und Studierende','Campusnetzwerke, dezentrale Koordination und schnelle Entscheidungen bildeten das Fundament. Studierende von Universitäten, Colleges und Madrasas überwanden alte Trennlinien.','Chronologie lesen','#timeline'],['Frauen und gewöhnliche Menschen','Studentinnen standen von Beginn an vorn. Arbeiter, Eltern, Lehrkräfte, Ärzte, Juristen, Künstler, Rikschafahrer und Händler machten aus Studentenprotest einen Volksaufstand.','Frauen im Aufstand ↗','https://www.thedailystar.net/news/bangladesh/news/inside-july-uprising-women-led-nation-followed-3950221'],['Digitaler und Diaspora-Widerstand','Trotz Abschaltung transportierten Videos, Graffiti, Musik, Übersetzungen und internationale Öffentlichkeitsarbeit Belege über Grenzen. Diaspora-Proteste und wirtschaftliche Nichtzusammenarbeit erhöhten den Druck.','Rolle der Diaspora ↗',SOURCES[8].url]],
    ncpKicker:'Eine neue politische Reise nach dem Juli',ncpTitle:'Einige Organisatoren wurden später Gründungsführer der NCP',ncpClarification:'<b>Historische Klarstellung:</b> Die National Citizen Party (NCP) existierte im Juli 2024 noch nicht. Sie wurde am 28. Februar 2025 gegründet. Ihre damalige Rolle war die von Koordinatoren und Organisatoren der Students Against Discrimination—nicht die von NCP-Führungskräften.',ncpText:'Nahid Islam, Akhtar Hossen, Hasnat Abdullah und Sarjis Alam gehörten zu den jungen Persönlichkeiten der Bewegung, die später der Gründungsführung der NCP beitraten. Nahids Ein-Punkt-Erklärung vom 3. August sowie Haft und mutmaßliche Folter von Koordinatoren prägen die Geschichte dieser politischen Generation. Doch der Juli war ein breiter Aufstand über Parteien, Ansichten, Klassen und Identitäten hinweg—kein Eigentum einer später gegründeten Partei.',ncpSourceOne:'AP · Hintergrund der NCP-Gründung ↗',ncpSourceTwo:'BSS · Gründungsführung ↗',
    diasporaKicker:'Widerstand über Grenzen',diasporaTitle:'Das Internet stoppte; die Solidarität nicht',diasporaText:'Als die Kommunikation abriss, übersetzten und verbreiteten Diaspora-Gemeinschaften Informationen, wandten sich an internationale Medien und Menschenrechtsgruppen, protestierten vor Auslandsvertretungen und übten mit einem Remittance-Boykott Druck aus. Aktionen in Frankfurt, Darmstadt und anderen deutschen Städten waren Teil dieser Solidarität.',diasporaClarification:'<b>Klarstellung:</b> Dies war der Beitrag der breiteren bangladeschischen Diaspora 2024. Die später entstandene NCP Diaspora Alliance Germany bewahrt diese Erinnerung, beansprucht aber nicht, alle damaligen Aktionen organisiert zu haben.',diasporaSource:'Bericht über die Diaspora lesen ↗',
    legacyKicker:'Das unerfüllte Versprechen des Juli',legacyTitle:'Sieg ist mehr als ein Machtwechsel',pledges:[['Wahrheit und Gerechtigkeit','Unabhängige, unparteiische und opferzentrierte Untersuchung jeder Tötung und Folter.'],['Institutionelle Rechenschaft','Polizei, Geheimdienste, Justiz und Wahlen aus parteipolitischer Vereinnahmung lösen.'],['Gleiche Bürgerschaft','Sicherheit und gleiche Rechte für Frauen, Minderheiten, Indigene, Menschen mit Behinderungen und Andersdenkende.'],['Erinnerung und Bildung','Namen, Zeugnisse und Belege bewahren; geprüfte Geschichte statt Desinformation lehren.']],
    sourcesKicker:'Selbst nachprüfen',sourcesTitle:'Primärberichte und Bibliothek',sourcesIntro:'Diese Seite ist ein Einstieg. Die Originalquellen enthalten ausführliche Zeugnisse, Opferlisten, Fotografie und Untersuchungen.',sourceTitles:['Fact-Finding-Bericht zu Menschenrechtsverletzungen im Juli und August 2024','Vorläufige Analyse der Proteste und Unruhen in Bangladesch','Mindestens 32 Kinder bei der Gewalt in Bangladesch getötet','Was geschah bei den Protesten für eine Quotenreform?','Tausende Demonstrierende willkürlich festgenommen','Von der Quote zur Staatsreform—Chronologie des Juli-Aufstands','36 Tage im Juli—Berichte, Zeugnisse und Recherchen','Foto- und Dokumentenarchiv des Juli-Aufstands','Wie die bangladeschische Diaspora die Juli-Bewegung unterstützte','Führungspersönlichkeiten des Aufstands gründen die National Citizen Party','Offizieller Start der National Citizen Party','Aufruf zu Gerechtigkeit und Schutz nach dem Machtwechsel'],sourceMeta:['UN-Menschenrechtsbüro · 12. Februar 2025','UN-Menschenrechtsbüro · 16. August 2024','UNICEF Südasien · 2. August 2024','Amnesty International · Juli 2024','Amnesty International · 2. August 2024','Chronologie mit verlinkten Berichten · 2018–5. August 2024','Multimedia-Archiv · 2026','Öffentliches Archiv der Regierung Bangladeschs','Diaspora-Bericht einschließlich Deutschland · 5. September 2024','Associated Press · 28. Februar 2025','Bangladesh Sangbad Sangstha · 28. Februar 2025','Generalsekretär der Vereinten Nationen · 5. August 2024'],closingKicker:'Von Erinnerung zu Verantwortung',closingTitle:'Ihr Blut brach die Angst;<br>ihre Träume müssen den Staat formen.',closingText:'An den Juli zu erinnern ist kein Aufruf zur Rache. Es bedeutet Wahrheit, unparteiische Aufklärung jedes Todes, Menschenwürde und Institutionen, mit denen keine Regierung Bürger durch Kugeln, Haft oder Internetsperren zum Schweigen bringen kann.',shareArchive:'Dieses Archiv teilen',footerNote:'Eine Initiative für politische Bildung und die Bewahrung historischen Gedächtnisses',mainSite:'Hauptwebsite',sourceNav:'Quellen',backTop:'Nach oben ↑',copied:'Link kopiert.'
  };

  const content = { bn, en, de };
  let language = 'bn';

  function sourceLink(number) {
    const source = SOURCES[number - 1];
    return source ? `<a class="citation" href="${source.url}" target="_blank" rel="noopener noreferrer" aria-label="Source ${number}: ${source.org}">${number}</a>` : '';
  }

  function render(lang) {
    const c = content[lang] || bn;
    document.documentElement.lang = lang;
    document.title = lang === 'bn' ? 'জুলাই ২০২৪ — ৩৬ দিনের গণঅভ্যুত্থান | NCPDA Germany' : lang === 'de' ? 'Juli 2024 — 36 Tage Volksaufstand | NCPDA Germany' : 'July 2024 — 36 Days of Uprising | NCPDA Germany';
    document.querySelectorAll('[data-copy]').forEach((el) => {
      const value = c[el.dataset.copy];
      if (typeof value === 'string') el.innerHTML = value;
    });
    document.querySelectorAll('[data-lang]').forEach((button) => button.setAttribute('aria-pressed', String(button.dataset.lang === lang)));

    document.getElementById('fact-grid').innerHTML = c.facts.map((fact) => `<article class="fact" data-reveal><strong>${fact.n}</strong><span>${fact.label}</span><small>${fact.note}</small>${sourceLink(fact.s)}</article>`).join('');
    document.getElementById('timeline-list').innerHTML = c.timeline.map((item) => `<li class="timeline-item${item.breaking ? ' breaking' : ''}" data-reveal><time class="timeline-date">${item.date}</time><article class="timeline-content"><span class="timeline-tag">${item.tag}</span><h3>${item.title}</h3><p>${item.text} ${item.src.map(sourceLink).join('')}</p></article></li>`).join('');
    document.getElementById('violation-grid').innerHTML = c.violations.map((item) => `<article class="violation" data-reveal><b>${item[0]}</b><p>${item[1]}</p></article>`).join('');
    document.getElementById('photo-grid').innerHTML = c.photos.map((photo) => `<figure class="photo-card" data-reveal><img src="${photo.src}" alt="${photo.alt}" loading="lazy" decoding="async"><figcaption class="photo-caption"><b>${photo.title}</b><small>${photo.credit}</small></figcaption></figure>`).join('');
    document.getElementById('people-grid').innerHTML = c.people.map((item, index) => `<article class="people-card" data-reveal><span class="index">0${index + 1}</span><h3>${item[0]}</h3><p>${item[1]}</p><a href="${item[3]}"${item[3].startsWith('http') ? ' target="_blank" rel="noopener noreferrer"' : ''}>${item[2]}</a></article>`).join('');
    document.getElementById('pledge-grid').innerHTML = c.pledges.map((item) => `<article class="pledge" data-reveal><b>${item[0]}</b><p>${item[1]}</p></article>`).join('');
    document.getElementById('source-list').innerHTML = SOURCES.map((source, index) => `<a class="source" href="${source.url}" target="_blank" rel="noopener noreferrer" data-reveal><span class="source-number">${String(index + 1).padStart(2,'0')}</span><span><b>${c.sourceTitles[index]}</b><small>${c.sourceMeta[index]}</small></span><span class="source-arrow">↗</span></a>`).join('');
    localStorage.setItem('july-archive-lang', lang);
    observeReveals();
  }

  let observer;
  function observeReveals() {
    if (observer) observer.disconnect();
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) {
      document.querySelectorAll('[data-reveal]').forEach((el) => el.classList.add('visible'));
      return;
    }
    observer = new IntersectionObserver((entries) => entries.forEach((entry) => {
      if (entry.isIntersecting) {
        entry.target.classList.add('visible');
        observer.unobserve(entry.target);
      }
    }), { threshold: .08, rootMargin: '0px 0px -30px' });
    document.querySelectorAll('[data-reveal]').forEach((el) => observer.observe(el));
  }

  async function shareArchive() {
    const c = content[language];
    const shareUrl = new URL(location.href);
    shareUrl.hash = '';
    const shareData = { title: document.title, text: c.heroLead.replace(/<[^>]+>/g,''), url: shareUrl.href };
    try {
      if (navigator.share) await navigator.share(shareData);
      else await navigator.clipboard.writeText(shareData.url);
      document.getElementById('share-status').textContent = c.copied;
    } catch (error) {
      if (error.name !== 'AbortError') document.getElementById('share-status').textContent = shareData.url;
    }
  }

  document.querySelectorAll('[data-lang]').forEach((button) => button.addEventListener('click', () => {
    language = button.dataset.lang;
    const url = new URL(location.href);
    if (language === 'bn') url.searchParams.delete('lang'); else url.searchParams.set('lang', language);
    history.replaceState({}, '', url);
    render(language);
  }));
  document.getElementById('share-top').addEventListener('click', shareArchive);
  document.getElementById('share-bottom').addEventListener('click', shareArchive);
  addEventListener('scroll', () => {
    const max = document.documentElement.scrollHeight - innerHeight;
    document.getElementById('progress').style.width = `${max > 0 ? (scrollY / max) * 100 : 0}%`;
    document.querySelector('.site-header').classList.toggle('scrolled', scrollY > 30);
  }, { passive: true });

  const requested = new URLSearchParams(location.search).get('lang');
  const saved = localStorage.getItem('july-archive-lang');
  language = ['bn','en','de'].includes(requested) ? requested : (['bn','en','de'].includes(saved) ? saved : 'bn');
  render(language);
})();
